# Generated by Django 5.0.6 on 2024-07-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(default='oc/defaul.png', upload_to='')),
                ('descripcion', models.CharField(max_length=500)),
                ('fuerza', models.FloatField()),
                ('agilidad', models.FloatField()),
                ('crackilidad', models.FloatField()),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
            },
        ),
    ]
