# Generated by Django 5.0.6 on 2024-07-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='imagen',
            field=models.ImageField(default='oc/defaul.png', upload_to='oc'),
        ),
    ]
